import os
import sys
from time import sleep

os.system("termux-setup-storage")
os.system("pkg install sl")
os.system("clear")
os.system("pkg install figlet")
os.system("clear")
os.system("figlet Loading...")
sleep(2)
os.system("clear")
os.system("sl")
os.system("clear")
os.system("figlet ICA Tools Installer")
sleep(3)
print("===========================================")
print("=         Author : Mr.Hmei24/Ham          =")
print("=   Group Team : Islamic Cyber Attacker   =")
print("===========================================")
sleep(3)
print(" ")
print("[][][][][][][][][][][][][][][][][][][][][][][][][]")
print("[] Pilihlah Dengan Bijak Dan Teliti             []")
sleep(2)
print("[] Sekali Anda Masuk Utk Menginstall Tools      []")
sleep(2)
print("[] Maka Anda Tidak Akan Bisa Ke Menu Home Lagi  []")
sleep(2)
print("[] Kecuali Anda Mengulanginya Dari [cd]         []")
print("[][][][][][][][][][][][][][][][][][][][][][][][][]")
sleep(3)
print("")
print("Menu:")
print("0.Exit")
sleep(1)
print("1.Tool-X Installer")
sleep(1)
print("2.GGMUX Installer")
sleep(1)
print("3.Termux Login Installer")
sleep(1)
print("4.Hacker Keyboard In Termux")
sleep(1)
print("5.FBH Tools Installer")
sleep(1)
Pilih = input("Pilih Nomor = ")

if(Pilih == "5" ):
  print("")
  print("Installing Package...")
  sleep(3)
  print("Memulai...")
  print("")
  sleep(2)
  os.system("pkg upgrade && pkg update")
  os.system("pkg install git nano php")
  os.system("pkg install python && install python2 && install python3")
  os.system("git clone https://github.com/muhammadfathul/FBH")
  os.system("clear")
  os.system("figlet Succes")
  print("FBH Succes Installed")
  print("")
  sleep(2)
  print("Username : AsecC")
  print("Password : eror404")
  sleep(4)
  print("")
  print("")
  print("INGIN LANGSUNG MENCOBA TOOLS? (y/n)")
  if(Pilih == "y" ):
    os.system("cd FBH")
    os.system("bash setup")
    os.system("./FBH")
    os.system("help")
    os.system("Thanks You")
  if(Pilih == "n" ):
    print("")
    os.system("figlet Pergi Lu Sono")
    sleep(2)
    os.system("exit")

if(Pilih == "4" ):
  print("")
  print("Installing Package...")
  sleep(3)
  print("Memulai...")
  print("")
  sleep(2)
  os.system("pkg update && pkg upgrade")
  os.system("pkg install python")
  os.system("pkg install git")
  os.system("git clone https://github.com/karjok/terkey")
  os.system("clear")
  os.system("figlet Succes")
  print("Terkey Succes Installed")
  print("")
  print("INGIN LANGSUNG MENCOBA TOOLS? (y/n)")
  if(Pilih == "y" ):
    os.system("cd Terkey")
    os.system("python terkey.py")
    os.system("figlet Thank You")
  if(Pilih == "n" ):
    os.system("figlet Pergi Lu Sono")
    sleep(2)
    os.system("exit")
  os.system("figlet Thank You")
  print("")

if(Pilih == "3" ):
  print("")
  print("Installing Package...")
  sleep(3)
  print("Memulai...")
  print("")
  sleep(2)
  os.system("pkg install git python")
  os.system("clear")
  os.system("git clone https://github.com/Ublimjo/Termux-login.git")
  os.system("clear")
  os.system("figlet Succes")
  print("")
  print("Termux-Login Succes Installed")
  sleep(1)
  print("INGIN LANGSUNG MENCOBA TOOLS? (y/n)")
  if(Pilih == "y" ):
    os.system("cd Termux-login")
    os.system("bash setup.sh")
    os.system("figlet Thanks You")
  if(Pilih == "n" ):
    os.system("figlet Pergi Lu Sono")
    sleep(2)
    os.system("exit")

if(Pilih == "0" ):
  os.system("clear")
  os.system("figlet Pergi Lu Sono")
  print("")
  os.system("exit")

if(Pilih == "2" ):
  print("")
  print("Installing Package...")
  sleep(3)
  print("Memulai...")
  print("")
  sleep(2)
  os.system("pkg update && pkg upgrade")
  os.system("pkg install git")
  os.system("clear")
  os.system("pkg install cowsay")
  os.system("clear")
  os.system("pkg install lolcat")
  os.system("clear")
  os.system("pkg install figlet")
  os.system("clear")
  os.system("gem install lolcat")
  os.system("clear")
  os.system("git clone https://github.com/muhammadfathul/GGMUX")
  os.system("clear")
  os.system("figlet Succes")
  os.system("")
  print("GGMUX   Succes  Installed")
  sleep(1)
  print("")
  print("INGIN LANGSUNG MENCOBA TOOLS? (y/n)")
  if(Pilih == "n" ):
    os.system("figlet Pergi Lu Sono")
    os.system("exit")
  if(Pilih == "y" ):
    os.system("cd GGMUX")
    os.system("chmod 777 * ggmux.sh")
    os.system("./ggmux.sh")
    os.system("figlet Thanks You")
  print("")

if(Pilih == "1" ):
  print("")
  print("Installing Package...")
  sleep(2)
  print("Memulai...")
  print("")
  print("")
  sleep(1)
  os.system("pkg update && pkg upgrade")
  os.system("pkg install nano git php")
  os.system("pkg install python")
  os.system("git clone https://github.com/Rajkumrdusad/Tool-X")
  print(" ")
  print("Tool-X Succes Installed")
  sleep(1)
  print(" ")
  print("INGIN LANGSUNG MENCOBA TOOLS? (y/n)")
  if(Pilih == "y" ):
    os.system("cd Tool-X")
    os.system("chmod +x install.aex")
    os.system("./install.aex")
    os.system("figlet Thanks You")
  print(" ")
  if(Pilih == "n" ):
    os.system("figlet Pergi Lu Sono")
    sleep(1)
    os.system("exit")
