import os
import sys
from time import sleep

os.system("termux-setup-storage")
os.system("pkg install sl")
os.system("clear")
os.system("pkg install figlet")
os.system("clear")
os.system("figlet Loading...")
sleep(2)
os.system("clear")
os.system("sl")
os.system("clear")
os.system("figlet ICA Tools Installer")
sleep(3)
print("===========================================")
print("=         Author : Mr.Hmei24/Ham          =")
print("=   Group Team : Islamic Cyber Attacker   =")
print("===========================================")
sleep(3)
print(" ")
print("########################################")
print("Pilihlah Dengan Bijak Dan Teliti")
sleep(2)
print("Sekali Anda Masuk Utk Menginstall Tools")
sleep(2)
print("Maka Anda Tidak Akan Bisa Ke Menu Home Lagi")
sleep(2)
print("Kecuali Anda Mengulanginya Dari [cd]")
print("########################################")
sleep(3)
print("")
print("Menu:")
print("0.Exit")
print("1.Tool-X Installer")
print("2.GGMUX Installer")
print("3.Termux Login Installer")
print("4.Hacker Keyboard In Termux")
print("5.FBH Tools Installer")
Pilih = input("Pilih Nomor = ")

if(Pilih == "5" ):
  print("")
  print("Installing Package...")
  sleep(3)
  print("Memulai...")
  sleep(2)
  os.system("pkg upgrade && pkg update")
  os.system("pkg install git nano php")
  os.system("pkg install python && install python2 && install python3")
  os.system("git clone https://github.com/muhammadfathul/FBH")
  os.system("clear")
  os.system("figlet ==========")
  os.system("figlet FBH Installed")
  os.system("figlet ==========")
  os.system("figlet Next :")
  print("")
  print("Username : AsecC")
  print("Password : eror404")
  print("")
  print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
  print("$            cd FBH          $")
  print("$          bash setup        $")
  print("$            ./FBH           $")
  print("$             help           $")
  print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
  print("")
  os.system("figlet Thank You")
  print("")

if(Pilih == "4" ):
  print("")
  print("Installing Package...")
  sleep(3)
  print("Memulai...")
  sleep(2)
  os.system("pkg update && pkg upgrade")
  os.system("pkg install python")
  os.system("pkg install git")
  os.system("git clone https://github.com/karjok/terkey")
  os.system("clear")
  os.system("figlet ============")
  os.system("figlet Terkey Installed")
  os.system("figlet ============")
  os.system("figlet Next :")
  print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
  print("$          cd Terkey         $")
  print("$       python terkey.py     $")
  print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
  print("")
  os.system("figlet Thank You")
  print("")

if(Pilih == "3" ):
  print("")
  print("Installing Package...")
  sleep(3)
  print("Memulai...")
  sleep(2)
  os.system("cd ~")
  os.system("pkg install git python")
  os.system("clear")
  os.system("git clone https://github.com/Ublimjo/Termux-login.git")
  os.system("clear")
  os.system("figlet ===========")
  os.system("figlet Termux Login Installed")
  os.system("figlet ===========")
  os.system("figlet Next :")
  print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
  print("$       cd Termux-login      $")
  print("$        bash setup.sh       $")
  print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
  print("")
  os.system("figlet Thank You")
  print("")

if(Pilih == "0" ):
  os.system("figlet Pergi Sono")
  print("")
  os.system("exit")

if(Pilih == "2" ):
  print("")
  print("Installing Package...")
  sleep(3)
  print("Memulai...")
  sleep(2)
  os.system("pkg update && pkg upgrade")
  os.system("pkg install git")
  os.system("clear")
  os.system("pkg install cowsay")
  os.system("clear")
  os.system("pkg install lolcat")
  os.system("clear")
  os.system("pkg install figlet")
  os.system("clear")
  os.system("gem install lolcat")
  os.system("clear")
  os.system("git clone https://github.com/muhammadfathul/GGMUX")
  os.system("clear")
  os.system("figlet =============")
  os.system("figlet  GGMUX   Succes  Installed")
  os.system("figlet =============")
  os.system("figlet Next : ")
  print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
  print("$           cd GGMUX         $")
  print("$    chmod 777 * ggmux.sh    $")
  print("$          ./ggmux.sh        $")
  print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
  print("")
  os.system("figlet Thank You")
  print("")

if(Pilih == "1" ):
  print("")
  print("Installing Package...")
  sleep(3)
  print("Memulai...")
  sleep(2)
  os.system("pkg update && pkg upgrade")
  os.system("pkg install nano git php")
  os.system("pkg install python")
  os.system("git clone https://github.com/Rajkumrdusad/Tool-X")
  print(" ")
  print("Tool-X Berhasil Terinstall")
  os.system("figlet Next :")
  print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
  print("$          cd Tool-X         $")
  print("$    chmod +x install.aex    $")
  print("$        ./install.aex       $")
  print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
  print(" ")
  os.system("figlet Thank You")
  print(" ")
